name: Netlify CI/CD Workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

permissions:
  contents: read

jobs:
  integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint Code
        run: echo "Linting repository"

      - name: Run Unit Tests
        run: echo "Running unit tests"

  build-and-deploy-netlify:
    name: Continuous Deployment to Netlify
    needs: integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Adjust if necessary

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build # Adjust if needed based on your app's build command

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN:  nfp_1vY94pp7zwWN8EHctr35bBarqh49wQQna1ac
          NETLIFY_SITE_ID:  a0c950d2-007b-4bf4-af67-1ae000e4de9 
        run: |
          npm install -g netlify-cli
          netlify deploy --dir=build --prod --site=$NETLIFY_SITE_ID
